Website/CartApp/urls.py
from django.urls import path
from . import views
app_name='CartApp'

urlpatterns=[
    path('add/<int:product_id>/',views.Cart_add,name='cart_add'),
    path('',views.Cart_detail,name='cart_detail'),
    #path('remove/<int:product_id>/',views.Cart_remove,name='cart_remove'),
    #path('remove_all/<int:product_id>/',views.Cart_remove_all,name='cart_remove_all'),
]

Website/LoginApp/urls.py
from django.urls import path
from . import views

app_name='LoginApp'

urlpatterns=[
    path('',views.Detail,name='detail'),
    path('login/',views.Login,name='login'),
    path('signup/',views.SignUp,name='signup'),
]

Website/Shop/urls.py
from django.urls import path
from . import views
#app_name='Shop'

urlpatterns=[
    path('',views.Allproduct,name='allproduct'),
    path('<slug:c_slug>/',views.Allproduct,name='products_by_cat'),
    path('<slug:c_slug>/<slug:p_slug>/',views.Productdetail,name='productdetail'),
]

Website/Website/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static
from Shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('LoginApp.urls')),
    path('Shop/',include('Shop.urls')),
    path('search/',include('search.urls')),
    #path('cart/',include('CartApp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Website/search/urls.py
from django.urls import path
from . import views
app_name='search'

urlpatterns=[
    path('',views.Search,name='search1'),
]

Website/CartApp/models.py
from django.db import models
from Shop.models import Product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table="Cart"
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table="CartItem"
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return str(self.product)

Website/LoginApp/models.py
from django.db import models

class SignUpModel(models.Model):
    Name=models.CharField(max_length=200)
    Email=models.EmailField(primary_key=True)
    Password = models.CharField(max_length=200)

Website/Shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name=models.CharField(max_length=256,unique=True)
    slug=models.SlugField(max_length=256,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='Category/',blank=True)

    class Meta:
        ordering=['name']
        verbose_name_plural='Categories'

    def get_url(self):
        return reverse('products_by_cat',args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=256,unique=True)
    slug=models.SlugField(max_length=256,unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='Product/',blank=True)
    description=models.TextField(blank=True)
    price=models.IntegerField()
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created= models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name_plural='Products'

    def __str__(self):
        return self.name

Website/search/models.py
from django.db import models

# Create your models here.

Website/LoginApp/forms.py
from django import forms
from .models import SignUpModel

class SignUpForm(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    password=forms.CharField(widget=forms.PasswordInput)
    confirm_password=forms.CharField(widget=forms.PasswordInput)

class LoginForm(forms.Form):
    email=forms.EmailField()
    password=forms.CharField(widget=forms.PasswordInput)

Website/CartApp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from Shop.models import Product
from .models import *
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity<cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'CartApp/cart.html',dict(cart_items=cart_items,total=total,counter=counter))

Website/LoginApp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout


def Detail(request):
    return render(request,'LoginApp/detail.html')

def SignUp(request):
    sign=SignUpForm()
    if request.method=='POST':
        sign=SignUpForm(request.POST)
        if sign.is_valid():
            try:
                email=sign.cleaned_data['email']
                pas=sign.cleaned_data['password']
                user = User.objects.create_user(email,email,pas)
                user.save()
                return redirect('LoginApp:login')
            except:
                pass
    return render(request,'LoginApp/signup.html',{'sign':sign})

def Login(request):
    login=LoginForm()
    print("1")
    if request.method=='POST':
        print("2")
        login=LoginForm(request.POST)
        if login.is_valid():
            print("3")
            try:
                email=login.cleaned_data['email']
                pas=login.cleaned_data['password']
                print("4")

                user = authenticate(request,username=email, password=pas)
                print("5")
                if user:
                    print("6")
                    print(user)
                    login(request, user)
                    print("7")
                    return redirect('Shop:allproduct')

            except:
                pass
    return render(request,'LoginApp/login.html',{'login':login})

Website/Shop/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import *

def Home(request):
    return HttpResponse("This is home page of website")



def Allproduct(request,c_slug=None):
    categ=None
    if c_slug:
        categ=get_object_or_404(Category,slug=c_slug)
        products=Product.objects.filter(category=categ,available=True)
    else:
        products=Product.objects.filter(available=True)
    obj=Category.objects.all()
    print(obj)
    obj1=obj[0]
    obj2=obj[1]
    obj3=obj[2]
    return render(request,'Shop/allproduct.html',{'products':products,'categ':categ,'obj1':obj1,'obj2':obj2,'obj3':obj3})


def Productdetail(request,c_slug=None,p_slug=None):
    product=get_object_or_404(Product,slug=p_slug)
    return render(request,'Shop/productdetail.html',{'product':product})

Website/search/views.py
from django.shortcuts import render
from Shop.models import Product
from django.http import HttpResponse
from django.db.models  import Q


def Search(request):
    products=None
    query=None
    print('q' in request.POST)
    if 'q' in request.POST:
        query=request.POST.get('q')
        print("BBB",query)
        products=Product.objects.all().filter(Q(description__contains=query) | Q(name__contains=query))
    print("AAAA",products)
    print("BBB",query)
    return render(request,'search/search.html',{'query':query,'products':products})

Website/templates/LoginApp/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>Press <a href="{% url 'LoginApp:login' %}">here</a> fro login</h3>
    <h3>Press <a href="{% url 'LoginApp:signup' %}">here</a> fro signup</h3>
  </body>
</html>

Website/templates/LoginApp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      .signup
      {
        padding: 20px;
      }
      h1
      {
        padding: 20px;
        padding-left: 50px;
        font-size: 50px;
        font-weight: bold;
        color: #0000cc;
      }
      label
      {
        padding: 20px;
        padding-left: 50px;
        font-size: 30px;
        font-weight: bold;
        color: #990099;
      }
      input[type=email]
      {
        margin-left: 46px;
      }
      input[type=submit]
      {
        margin-top: 30px;
        margin-left: 100px;
        padding-left: 100px;
        border: 2px;
        background-color: #123646;
        text-decoration: none;
        font-weight: bold;
        font-size: 17px;
        line-height: 30px;
        border-radius: 4px;
        border: 2px solid black;
        -webkit-transition-duration: 0.4s; /* Safari */
        transition-duration: 0.4s;
        color: #FFFFFF;
        cursor: pointer;
        width: 20%;
        text-align: left;
      }

      input[type=submit]:hover
      {
        background-color: #373646;
        font-size: 21px;
        cursor: pointer;
        color: white;
      }
    </style>
  </head>

  <body style="background-image: url({% static 'image/img19.jpg' %});">
    <div class="signup">
      <form method="post">
        {% csrf_token %}
        <h1>Login Here:</h1>
        {{login.as_p}}
        <input type="submit" name="submit" value="Submit">
      </form>
    </div>
  </body>
</html>

Website/templates/LoginApp/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      .signup
      {
        padding: 20px;
      }
      h1
      {
        padding: 20px;
        padding-left: 50px;
        font-size: 50px;
        font-weight: bold;
        color: #0000cc;
      }
      label
      {
        padding: 20px;
        padding-left: 50px;
        font-size: 30px;
        font-weight: bold;
        color: #990099;
      }
      input[type=email]
      {
        margin-left: 46px;
      }
      input[type=submit]
      {
        margin-top: 30px;
        margin-left: 100px;
        padding-left: 100px;
        border: 2px;
        background-color: #123646;
        text-decoration: none;
        font-weight: bold;
        font-size: 17px;
        line-height: 30px;
        border-radius: 4px;
        border: 2px solid black;
        -webkit-transition-duration: 0.4s; /* Safari */
        transition-duration: 0.4s;
        color: #FFFFFF;
        cursor: pointer;
        width: 20%;
        text-align: left;
      }

      input[type=submit]:hover
      {
        background-color: #373646;
        font-size: 21px;
        cursor: pointer;
        color: white;
      }
    </style>
  </head>

  <body style="background-image: url({% static 'image/img19.jpg' %});">
    <div class="signup">
      <form method="post">
        {% csrf_token %}
        <h1>Sign Up Here:</h1>
        {{sign.as_p}}
        <input type="submit" name="submit" value="Submit">
      </form>
    </div>
  </body>
</html>

Website/templates/Shop/allproduct.html
{% extends 'Shop/base_site.html' %}
{% load static%}


{% block slide %}
{% if not categ %}
  <div class="slideshow-container">

  <div class="mySlides fade ">
    <div class="numbertext">1 / 3</div>
    <img src="{{obj1.image.url}}"  height=400px width=100%  alt="No image">
    <div class="text">Caption Text</div>
  </div>

  <div class="mySlides fade ">
    <div class="numbertext">2 / 3</div>
    <img src="{{obj2.image.url}}"  height=400px width=100% alt="No image">
    <div class="text">Caption Two</div>
  </div>

  <div class="mySlides fade ">
    <div class="numbertext">3 / 3</div>
    <img src="{{obj3.image.url}}"  height=400px width=100% alt="No image">
    <div class="text">Caption Three</div>
  </div>
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>
  <br>

  <div style="text-align:center">
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
  </div>
{% endif %}
{% endblock %}


{% block content %}
{% if categ %}
<img src="{{categ.image.url}}" height=400px width=100% alt="No categ">
{% endif %}

{% for product in products %}
<div class="allproduct">
  <a href="{% url 'productdetail' product.category.slug  product.slug %}"><img src="{{product.image.url}}" height=300px  width=350px  alt="image not found"></a>
  <p>{{product.name}}</p>
  <p>{{product.price}}</p>
</div>
{% endfor %}

<script>
    var slideIndex = 0;
showSlides();

function showSlides() {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 1000); // Change image every 2 seconds
}
</script>


{% endblock %}

Website/templates/Shop/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <style media="screen">
      body
      {
        background-color: #E9E9E9;
      }
      .sticky {
      position: fixed;
      top: 0;
      width: 100%;
      }
    </style>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <div id="wrapper">
      {% include 'Shop/navbar.html' %}
    </div>
    <div class="">
      {% block slide %}
      {% endblock %}

    </div>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    {% include 'Shop/footer.html' %}

    <script>
    window.onscroll = function() {myFunction()};

    var header = document.getElementById("wrapper");
    var sticky = header.offsetTop;

    function myFunction() {
      if (window.pageYOffset > sticky) {
        header.classList.add("sticky");
      } else {
        header.classList.remove("sticky");
      }
    }
    </script>
  </body>
</html>

Website/templates/Shop/footer.html
<div class="">
  <p>@copy: Vijay Web All Rights Reserved </p>
</div>

Website/templates/Shop/navbar.html
{% load static %}
<div class="navbar">

  <nav class="">
    <ul>
      <li><a href="{% url 'allproduct' %}"><img src="{% static 'Image/logo.png' %}" alt="no image" height=50px width=50px></a></li>
      <li><a href="{% url 'allproduct' %}">Home</a></li>
      <li> | </li>
      {% for cat in links %}
      <li><a href="{% url 'products_by_cat'  cat.slug %}">{{cat.name}}</a></li>
      {# <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>#}
      <li> | </li>
      {% endfor %}
      <form class="" action="{% url 'search:search1' %}" method="post">
        {% csrf_token %}
        <li><input type="text" name="q" value=""></li>
        <li><button type="submit" name="button">search</button></li>
      </form>

      <li>Your Cart( )</li>
    </ul>
  </nav>

</div>

Website/templates/Shop/productdetail.html
{% extends 'Shop/base_site.html' %}
{% block content %}
<img src="{{product.image.url}}" alt="image not found">
<h4>{{product.name}}</h4>
<h5>{{product.price}}</h5>
<h5>{{product.category}}</h5>
<h5>{{product.stock}}</h5>
<a href="#">Add to cart</a>
{% endblock %}

Website/templates/Shop/slide.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <title></title>
  </head>
  <body>
    <div class="slideshow-container">

    <div class="mySlides fade ">
      <div class="numbertext">1 / 3</div>
      <img src="{{obj1.image.url}}" alt="No image">
      <div class="text">Caption Text</div>
    </div>

    <div class="mySlides fade ">
      <div class="numbertext">2 / 3</div>
      <img src="{{obj2.image.url}}" alt="No image">
      <div class="text">Caption Two</div>
    </div>

    <div class="mySlides fade ">
      <div class="numbertext">3 / 3</div>
      <img src="{{obj3.image.url}}" alt="No image">
      <div class="text">Caption Three</div>
    </div>

  

    </div>
    <br>

    <div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
</div>






    {% if categ %}
    <img src="{{categ.image.url}}" height=400px width=100% alt="No categ">
    {% endif %}

    {% for product in products %}
    <div class="allproduct">
      <a href="{% url 'productdetail' product.category.slug product.slug %}"><img src="{{product.image.url}}" height=300px  width=350px  alt="image not found"></a>
      <p>{{product.name}}</p>
      <p>{{product.price}}</p>
    </div>
    {% endfor %}
<script>
    var slideIndex = 0;
showSlides();

function showSlides() {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>
  </body>
</html>

Website/templates/search/search.html
{% extends  'Shop/base_site.html' %}
{% load static %}
{% block title %}
  Search  -Perfect Cushion Store
{% endblock %}
{% block content %}
<p>You have search for:<b>{{query}}</b></p>
{% for product in products %}
  <a href="{{product.get_url}}"><img src="{{product.image.url}}" heifht=200px width=200px alt=""></a>
  <h4>{{product.name}}</h4>
  <p>Rs.{{product.price}}</p>
{% empty %}
<p>0 Result Found</p>
{% endfor %}
{% endblock %}